app: erange-admin-frontend
image: 539924878996.dkr.ecr.us-east-2.amazonaws.com/erange-admin-frontend-stage:build_72-commit_cef15a68f1886d01986c96c77c04bb35152a00cf
nodeport: 32000
application_port: 80
resources:
  limits:
    memory: "128Mi"
    cpu: "100m"
  requests:
    memory: "128Mi"
    cpu: "100m"
readinessProbe:
  enabled: true
  httpGet:
    scheme: HTTP
    path: /index.html
    port: 80
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1 
  failureThreshold: 3
livenessProbe:
  enabled: true
  httpGet:
    scheme: HTTP
    path: /index.html
    port: 80
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3   
startupProbe:
  enabled: true
  httpGet:
    scheme: HTTP
    path: /index.html
    port: 80
  failureThreshold: 30
  periodSeconds: 10
hpa:
  minReplicas: 1
  maxReplicas: 10
  metrics:
    resource:
      name: cpu
      targetAverageUtilization: 10
