app: erange-admin-backend
image: 539924878996.dkr.ecr.us-east-2.amazonaws.com/erange-admin-backend-stage:build_52-commit_47c4a04c5ed8a8d19d80f2826f0db96369efc9cd
nodeport: 32001
application_port: 8081
resources:
  limits:
    memory: "1Gi"
    cpu: "1"
  requests:
    memory: "512Mi"
    cpu: "500m"
readinessProbe:
  httpGet:
    path: /health-check
    port: 8081
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1 
  failureThreshold: 3
livenessProbe:
  httpGet:
    path: /health-check
    port: 8081
  periodSeconds: 5
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3   
startupProbe:
  httpGet:
    path: /health-check
    port: 8081
  failureThreshold: 30
  periodSeconds: 10
hpa:
  minReplicas: 2
  maxReplicas: 4
  metrics:
    resource:
      name: cpu
      targetAverageUtilization: 70
